# Generated by Django 6.0.1 on 2026-03-03 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Objectif', '0002_goals_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('status', models.CharField(choices=[('en cours', 'En cours'), ('terminer', 'Terminer'), ('abandonner', 'Abandonner')], max_length=50)),
                ('objectif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goalstasks', to='Objectif.goals')),
            ],
        ),
    ]
