# Generated by Django 6.0.1 on 2026-03-05 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Taches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.TimeField(auto_now=True)),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessiontask', to='Taches.tasks')),
            ],
        ),
    ]
