# Generated by Django 6.0.1 on 2026-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='heure_fin',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='heure_debut',
            field=models.TimeField(),
        ),
    ]
