# Generated by Django 6.0.1 on 2026-03-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0002_sessions_heure_fin_alter_sessions_heure_debut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='heure_debut',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='sessions',
            name='heure_fin',
            field=models.TimeField(),
        ),
    ]
