# Generated by Django 6.0.1 on 2026-03-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Session', '0003_alter_sessions_heure_debut_alter_sessions_heure_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='heure_fin',
            field=models.TimeField(null=True),
        ),
    ]
