# Generated by Django 6.0.2 on 2026-03-03 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Objectif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='etat',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Termier', 'Terminer')], default='En cours', max_length=50),
        ),
    ]
